version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
     - '6379:6379'

  remote_server:
    image: dosuzer/cadastral_endpoint:latest
    container_name: remote_server
    ports:
     - '8001:8001'

  backend:
    build: .
    restart: always
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - data:/app/database
    links:
      - redis
    depends_on:
      - remote_server
      - redis

  celery:
    build: .
    command: celery -A cadastral_proccess worker -l info
    volumes:
      - data:/app/database
    depends_on:
      - redis

volumes:
  data: